# Site settings
title: |
  Open Knowledge International
  Annual Report
description: Looking back on 2015

googleanalytics: UA-76606733-1

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
